services:
  - type: web
    name: business-card-reader
    env: ruby
    buildCommand: "./bin/rails assets:precompile"
    # migrate を起動前に毎回実行（Free/SQLite の揮発環境で最速起動用）
    startCommand: "./bin/rails db:migrate && ./bin/rails server"
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true